apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - ingress.yaml
  - certificate.yaml
  - middleware.yaml
  - dashboard-windows.yaml
  - dashboards/nginx-metrics-dashboard.yaml
  - dashboards/nginx-logs-dashboard.yaml
  - dashboards/traces-dashboard.yaml