apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 1h
  chart:
    spec:
      chart: alloy
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    alloy:
      configMap:
        create: true
        content: |
          otelcol.receiver.otlp "default" {
            grpc { endpoint = "0.0.0.0:4317" }
            http { endpoint = "0.0.0.0:4318" }
            output {
              traces = [otelcol.exporter.otlp.tempo.input]
            }
          }

          otelcol.exporter.otlp "tempo" {
            client {
              endpoint = "tempo.tempo.svc.cluster.local:4317"
              tls { insecure = true }
            }
          }
    service:
      extraPorts:
        - name: otlp-grpc
          port: 4317
          targetPort: 4317
          protocol: TCP
        - name: otlp-http
          port: 4318
          targetPort: 4318
          protocol: TCP
    controller:
      type: daemonset
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule