apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: alloy
spec:
  interval: 1h
  chart:
    spec:
      chart: grafana-alloy
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    alloy:
      extraConfig: |
        otelcol.receiver.otlp "default" {
          grpc { endpoint = "0.0.0.0:4317" }
          http { endpoint = "0.0.0.0:4318" }
          output {
            traces = [otelcol.exporter.otlp.tempo.input]
          }
        }

        otelcol.exporter.otlp "tempo" {
          client {
            endpoint = "tempo.tempo.svc.cluster.local:4317"
            tls { insecure = true }
          }
        }
    controller:
      type: daemonset
    tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule