apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tempo-push
  namespace: tempo
spec:
  tls:
    - hosts:
        - lia-kube.cloudist.solutions
      secretName: tempo-tls-secret
  rules:
    - host: lia-kube.cloudist.solutions