apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/tempo
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: tempo
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: tempo
  - path: patch-certificate.yaml
    target:
      kind: Certificate
      name: tempo-tls
  - path: patch-ingress-push.yaml
    target:
      kind: Ingress
      name: tempo-push