apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  test:
    enable: true
  values:
    replicaCount: 2
    service:
      port: 80
    ingress:
      enabled: false
