apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/nginx
patches:
  - path: helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: nginx
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: nginx
  - path: patch-certificate.yaml
    target:
      kind: Certificate
      name: nginx-tls