apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  values:
    server:
      persistentVolume:
        enabled: true
        size: 8Gi
      statefulSet:
        enabled: true
      extraArgs:
        web.config.file: /etc/web-config/web-config.yml
      extraVolumes:
        - name: web-config
          secret:
            secretName: prometheus-basic-auth
      extraVolumeMounts:
        - name: web-config
          mountPath: /etc/web-config