apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: staging
resources:
  - namespace.yaml
  - nginx-app.yaml        # Deployment + Service
  - nginx-network-policy.yaml
  - nginx-ingress.yaml
  - RBAC.yaml
  - infrastructure-traefik.yaml  # Inkluderar HelmRepo + Release
  - podinfo-kustomization.yaml 
  - podinfo-source.yaml
  - monitoring/

