apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - flux-system/
  - ../../infrastructure/controllers/kustomization.yaml
  - ../../infrastructure/configs/kustomization.yaml
  - apps.yaml

