---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-global-policy
  namespace: nginx
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {} # Tillåt trafik från alla namespaces (Traefik)
    ports:
    - protocol: TCP
      port: 80
  egress:
  - to: [] # Detta tillåter ALL Egress (viktigt för svarstrafik!)
