---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: nginx-allow-all-temporary
  namespace: nginx
spec:
  podSelector: {} # Väljer ALLA poddar i namespacet
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - {} # Tillåt ALLT in
  egress:
  - {} # Tillåt ALLT ut
