---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-manager-sa
  namespace: nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-full-access-role
  namespace: nginx
rules:
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-manager-binding
  namespace: nginx
subjects:
  - kind: ServiceAccount
    name: nginx-manager-sa
    namespace: nginx
roleRef:
  kind: Role
  name: nginx-full-access-role
  apiGroup: rbac.authorization.k8s.io

--- 

# 1. Definiera VAD Traefik får göra i monitoring-namespacet
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: traefik-secret-reader
  namespace: monitoring # Viktigt!
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]

---
# 2. Koppla Traefiks ServiceAccount till denna Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: traefik-read-auth-secrets
  namespace: monitoring # Viktigt!
subjects:
  - kind: ServiceAccount
    name: traefik          # Namnet på Traefiks ServiceAccount
    namespace: flux-system # Var Traefik faktiskt bor
roleRef:
  kind: Role
  name: traefik-secret-reader
  apiGroup: rbac.authorization.k8s.io
