---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nginx-manager-sa
  namespace: nginx
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-full-access-role
  namespace: nginx
rules:
  - apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - list
  - watch
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "endpoints"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses", "networkpolicies"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-manager-binding
  namespace: nginx
subjects:
- kind: ServiceAccount
  name: nginx-manager-sa
  namespace: nginx
roleRef:
  kind: Role
  name: nginx-full-access-role
  apiGroup: rbac.authorization.k8s.io
