apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  ports:
  - name: http
    port: 8000          # ← LÄRARENS PORT! Service exponerar 8000
    targetPort: 8000    # Nginx pod lyssnar på 8000
  selector:
    app: {{ .Release.Name }}

