apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: http-to-https
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: "HostRegexp(`{host:.+}`) && !PathPrefix(`/.well-known/acme-challenge`)"
      kind: Rule
      priority: 1
      middlewares:
        - name: redirect-to-https
          namespace: traefik
      services:
        - name: noop@internal
          kind: TraefikService