apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-alloy
  namespace: flux-system
spec:
  interval: 1h
  url: oci://registry-1.docker.io/bitnamicharts/grafana-alloy
  ref:
    tag: 1.0.7