apiVersion: v1
kind: Secret
metadata:
  name: basic-auth-secret
  namespace: monitoring
type: Opaque
stringData:
  users: |
    admin:$apr1$45u83qms$P0TXCzfdh9zmsGf.bflb60

    # Format: username:password (Apache htpasswd format)
    # Generera med: htpasswd -c auth admin
