apiVersion: v1
kind: Secret
metadata:
  name: grafana-basic-auth
  namespace: monitoring
type: Opaque
stringData:
  users: |
    users: YWRtaW46e1NIQX1XNnBoNU1tNVB6OEdnaVVMYlBnekczN21qOWc9

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: grafana-auth
  namespace: monitoring
spec:
  basicAuth:
    secret: grafana-basic-auth
