apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: my-prometheus-stack
  namespace: monitoring
spec:
  releaseName: my-prometheus-stack
  targetNamespace: monitoring
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    prometheus:
      prometheusSpec:
        externalUrl: "https://monitoring.example.com/prometheus"
        routePrefix: /prometheus
        retention: 15d
    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin # Vi använder secret för lösenord
      podSecurityContext:
        runAsNonRoot: true
        fsGroup: 472
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 472
      grafana.ini:
        server:
          root_url: "https://monitoring.example.com/grafana/"
          serve_from_sub_path: true
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - monitoring.example.com
        paths:
          - /grafana
        tls:
          - secretName: monitoring-tls
            hosts:
              - monitoring.example.com

