apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: my-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  timeout: 10m

  releaseName: my-prometheus-stack
  targetNamespace: monitoring
  storageNamespace: monitoring

  chart:
    spec:
      chart: kube-prometheus-stack
      version: 55.8.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system

  install:
    createNamespace: true
    crds: CreateReplace

  upgrade:
    crds: CreateReplace
    cleanupOnFail: true

  values:

    # =========================
    # PROMETHEUS
    # =========================
    prometheus:
      prometheusSpec:
        retention: 2d
        externalUrl: "https://monitoring.example.com/prometheus"
        routePrefix: /prometheus

        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1Gi

        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 5Gi

    # =========================
    # GRAFANA
    # =========================
    grafana:
      enabled: true

      adminPassword: "ChangeMeNow123!"

      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi

      podSecurityContext:
        runAsNonRoot: true
        fsGroup: 472

      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 472

      grafana.ini:
        server:
          root_url: "https://monitoring.example.com/grafana/"
          serve_from_sub_path: true

      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
        hosts:
          - monitoring.example.com
        paths:
          - /grafana
        tls:
          - secretName: monitoring-tls
            hosts:
              - monitoring.example.com

    # =========================
    # Disable heavy components
    # =========================
    alertmanager:
      enabled: false

    kubeEtcd:
      enabled: false

    kubeScheduler:
      enabled: false

    kubeControllerManager:
      enabled: false

