apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns-grafana.yaml      # Ny
  - ns-prometheus.yaml   # Ny
  - ns-monitoring.yaml   # Behåll för Middleware/Security
  - source.yaml
  - security.yaml        # Middleware skapas här
  - release.yaml
  - grafana-network-policy.yaml
  - nginx-monitor.yaml
