apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - cert-issuer.yaml
  - network-policy.yaml
  - servicemonitor.yaml
  - helmreleases/
  - auth-middleware/
