apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ns-monitoring.yaml  # Skapa namespacet först!
  - source.yaml
  - grafana-network-policy.yaml
  - release.yaml
  - security.yaml
  - nginx-monitor.yaml
