apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 1h
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.7.0" # Det är bra praxis att låsa versionen
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    prometheus:
      prometheusSpec:
        # Tillåt Prometheus att hitta ServiceMonitors i ALLA namespaces
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {} 
    grafana:
      enabled: true
      ingress:
        enabled: false
        ingressClassName: traefik
        annotations:
          # 1. Här lägger vi till 'monitoring-redirect-https@kubernetescrd' först i listan
          traefik.ingress.kubernetes.io/router.middlewares: |
            redirect-https@kubernetescrd,  
            grafana-auth@kubernetescrd,     
            grafana-headers@kubernetescrd   
          # 2. Här kopplar vi på Cert-Manager
          cert-manager.io/cluster-issuer: "selfsigned-issuer"
        hosts:
          - grafana.local
        path: /
        # 3. Här aktiverar vi TLS (HTTPS)
        tls:
          - secretName: grafana-tls-cert
            hosts:
              - grafana.local
