apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: prometheus
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "61.7.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    # --- PROMETHEUS KONFIGURATION ---
    prometheus:
      prometheusSpec:
        # Berättar för Prometheus att den bor på /prometheus
        externalUrl: "https://194.103.192.81/prometheus"
        routePrefix: /prometheus
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: monitoring-grafana-auth@kubernetescrd,monitoring-redirect-https@kubernetescrd
          cert-manager.io/cluster-issuer: "selfsigned-issuer"
        hosts: [] 
        path: /prometheus
        pathType: Prefix
        tls:
          - secretName: prometheus-tls-cert
            hosts: []

# --- GRAFANA KONFIGURATION ---
    grafana:
      enabled: true
      namespaceOverride: "grafana"
      admin:
        existingSecret: "grafana-admin-auth"
        userKey: admin-user
        passwordKey: admin-password

      # Berättar för Grafana att den bor på /grafana
      grafana.ini:
        server:
          root_url: "https://194.103.192.81/grafana/"
          serve_from_sub_path: true
      
      ingress:
        enabled: true
        ingressClassName: traefik
        annotations:
          traefik.ingress.kubernetes.io/router.middlewares: monitoring-grafana-auth@kubernetescrd,monitoring-redirect-https@kubernetescrd
          cert-manager.io/cluster-issuer: "selfsigned-issuer"
        hosts: []
        path: /grafana
        pathType: Prefix
        tls:
          - secretName: grafana-tls-cert-v2
            hosts: []
