apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ubuntu-local
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: ubuntu-local
  endpoints:
    - port: metrics
      interval: 30s
---
apiVersion: v1
kind: Service
metadata:
  name: ubuntu-local
  namespace: monitoring
  labels:
    app: ubuntu-local
spec:
  type: ExternalName
  externalName: 172.20.102.29
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
```

## STEG 3: Spara filen
```
Ctrl+O
Enter
Ctrl+X
