apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - middleware.yaml
  - middleware-external.yaml
  - ingress.yaml
  - ingress-pushgateway.yaml
  - certificate.yaml
  - alertmanager-ingress.yaml
  - windows-exporter-config.yaml