apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: bitnami-nginx
    namespace: flux-system
  values:
    service:
      type: ClusterIP
      port: 80
    metrics:
      enabled: true